services:
  connection.factory.memcached:
    class: Vain\Memcache\Connection\Factory\MemcachedConnectionFactory
    arguments: ['memcached']
    tags:
      - {name: connection.factory}
  cache.factory.memcached:
    class: Vain\Memcache\Cache\Factory\MemcacheCacheFactory
    arguments: ['memcached']
    tags:
      - {name: cache.factory}
  connection.factory.memcached.proxy:
    class: Vain\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.memcached.doctrine
    decoration_priority: 100
    arguments: ['@connection.factory.memcached.proxy.inner']
