parameters:
  memcached.cache.name: 'memcached'

services:
  connection.memcached:
    class: Vain\Memcache\Connection\MemcachedConnection
    factory: ['@connection.factory.memcached', 'createConnection']
    arguments:
      - '%memcached.cache.name%'
  connection.factory.memcached:
    parent: connection.factory.abstract
    class: Vain\Memcache\Connection\Factory\MemcachedConnectionFactory
  cache.factory.memcached:
    class: Vain\Memcache\Cache\Factory\MemcacheCacheFactory
    arguments: ['memcached']
    tags:
      - {name: cache.factory}
  connection.factory.memcached.proxy:
    class: Vain\Core\Connection\Factory\Decorator\Proxy\ConnectionFactoryProxyDecorator
    decorates: connection.memcached.doctrine
    decoration_priority: 100
    arguments: ['@connection.factory.memcached.proxy.inner']
