parameters:
  memcached.config.required.fields: ['host', 'port']

services:
  connection.factory.memcached.trust:
    class: Vain\Memcache\Connection\Factory\MemcachedConnectionFactory
    arguments: ['memcached']
    tags:
      - {name: connection.factory}
  connection.factory.memcached.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    decorates: connection.factory.memcached.trust
    arguments: ['@connection.factory.memcached.assert.inner', '%memcached.config.required.fields%']
  connection.factory.memcached: '@connection.factory.memcached.assert'
  cache.factory.memcached:
    class: Vain\Memcache\Cache\Factory\MemcacheCacheFactory
    arguments: ['memcached']
    tags:
      - {name: cache.factory}
