parameters:
  memcached.connection.name: 'memcached'

services:
  connection.memcached:
    parent: connection.abstract
    class: Vain\Memcache\Connection\MemcachedConnection
    arguments: ['%memcached.connection.name%']
  cache.factory.memcached:
    class: Vain\Memcache\Cache\Factory\MemcacheCacheFactory
    arguments: ['memcached']
    tags:
      - {name: cache.factory}